# Generated by Django 3.2.19 on 2024-01-06 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 22, 30, 16, 842938)),
        ),
    ]
