# Generated by Django 3.2.19 on 2024-02-02 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_pageview_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 2, 15, 5, 7, 958245)),
        ),
    ]
