# Generated by Django 3.2 on 2024-11-02 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_pageview_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 2, 13, 15, 46, 916663)),
        ),
    ]
