# Generated by Django 3.2.6 on 2024-10-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_product_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='order_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed')], default='completed', max_length=10, null=True),
        ),
    ]
