# Generated by Django 3.2 on 2024-10-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_auto_20241013_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('salesperson', 'Salesperson'), ('manager', 'Manager')], max_length=15),
        ),
    ]
