# Generated by Django 3.2 on 2024-10-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_auto_20241022_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleproduct',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
