# Generated by Django 3.2 on 2024-10-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_saleproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('salesperson', 'Salesperson'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('managing_pharmacist', 'Managing_Pharmacist')], max_length=25),
        ),
    ]
