# Generated by Django 3.2 on 2024-10-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0014_alter_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacy',
            old_name='is_supervised_by',
            new_name='supervised_by',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(choices=[('opiods', 'Opiods'), ('overthecounter', 'OverTheCounter'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('supervising_pharmacist', 'Supervising_Pharmacist')], default='overthecounter', max_length=25),
        ),
    ]
