# Generated by Django 3.2 on 2024-10-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0016_user_bossed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.CharField(choices=[('opiods', 'Opiods'), ('overthecounter', 'OverTheCounter'), ('prescription_based', 'Prescription_Based')], default='overthecounter', max_length=25),
        ),
    ]
